Repository hybsearch/hybsearch, pull requests merged in 2018-03, with the labels that each got.

#67 Include a docker-compose.yml file
  server/docker-compose.yml
Labels: enhancement

#78 Clean up the electron-builder config
  .gitignore
  electron/package-lock.json
  electron/package.json
  server/package-lock.json
  server/package.json
Labels: refactoring

#77 Centralize #phylogram clearing
  electron/graph.js
Labels: refactoring

#75 Tweak the Prettier config a bit
  .prettierignore
  electron/package.json
  package.json
  server/package.json
Labels: refactoring

#80 Cache the pipeline
  electron/index.css
  electron/index.html
  electron/run.js
  electron/ui.js
  server/Dockerfile
  server/lib/prune-newick.js
  server/package-lock.json
  server/package.json
  server/pipeline/cache.js
  server/pipeline/hyb-pipeline
  server/pipeline/worker.js
  server/server.js
Labels: enhancement, refactoring

#83 Declaratively specify that we would like to use amd64 node images
  server/Dockerfile
Labels: enhancement

#85 Upgrade pip when building Docker image
  server/Dockerfile
Labels: enhancement

#86 First Pass at Multi-Staged Build
  server/.dockerignore
  server/Dockerfile
Labels: enhancement
